export const types = {
    SET_USER: "SET_USER",
    SET_LOGIN_MODAL: "SET_LOGIN_MODAL",
    SET_CURRENT_DRAWL: "SET_CURRENT_DRAWL",
    SET_IS_LOADER: "SET_IS_LOADER",
    SET_CONTRACT_DATA: "SET_CONTRACT_DATA",
}