const SET_TIME = 'SET_TIME';
const SET_FORMAT = 'SET_FORMAT';
const SET_MINT_PAUSE = 'SET_MINT_PAUSE';
const SET_MINT_OVER = 'SET_MINT_OVER';
const SET_OPEN_DRAW_POPUP = 'SET_OPEN_DRAW_POPUP';
const SET_OPEN_SAVE_POPUP = 'SET_OPEN_SAVE_POPUP';
const SET_NIGHT_MODE = 'SET_NIGHT_MODE';
const SET_BALANCE = 'SET_BALANCE';
const SET_LOADING = 'SET_LOADING';
const SET_OPEN_DEFAULT_POPUP = 'SET_OPEN_DEFAULT_POPUP';
const SET_DEFAULT_POPUP_PROPS = 'SET_DEFAULT_POPUP_PROPS';

const MINT_TYPES = {
	SET_TIME,
	SET_FORMAT,
	SET_MINT_PAUSE,
	SET_MINT_OVER,
	SET_OPEN_DRAW_POPUP,
	SET_OPEN_SAVE_POPUP,
	SET_NIGHT_MODE,
	SET_BALANCE,
	SET_LOADING,
	SET_OPEN_DEFAULT_POPUP,
	SET_DEFAULT_POPUP_PROPS
};

export default MINT_TYPES;
