const SET_TIME = 'SET_TIME';
const SET_FORMAT = 'SET_FORMAT';
const SET_MINT_PAUSE = 'SET_MINT_PAUSE';
const SET_MINT_OVER = 'SET_MINT_OVER';
const SET_OPENED_DRAW_POPUP = 'SET_OPENED_DRAW_POPUP';
const SET_OPEN_SAVE_POPUP = 'SET_OPEN_SAVE_POPUP';

const MINT_TYPES = {
	SET_TIME,
	SET_FORMAT,
	SET_MINT_PAUSE,
	SET_MINT_OVER,
	SET_OPENED_DRAW_POPUP,
	SET_OPEN_SAVE_POPUP
};

export default MINT_TYPES;
